// You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.

// A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.

#include <bits/stdc++.h> 

void solve(string str, vector<string>&ans, string temp, int i){
    if (i >= str.length()){
        if (temp.size() != 0){
            ans.push_back(temp) ;
        }
        return ;
    }

    //exclude
    solve(str, ans, temp, i+1) ;

    //include
    temp += str[i] ;
    solve(str, ans, temp, i+1) ;
}

vector<string> subsequences(string str){
	
	vector<string> ans ;
    string temp = "" ;
    solve(str, ans, temp, 0) ;
    return ans ;
	
}
